# Generated by Django 5.1.1 on 2024-09-11 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_chatroom_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                null=True, related_name="chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
