# Generated by Django 5.1.1 on 2024-09-11 17:50

import core.constants
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easebrain", "0007_alter_userprofile_birthdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "ADMIN"), ("user", "USER")],
                default=core.constants.UserRoleEnum["USER"],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "MALE"), ("Female", "FEMALE")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="maritalStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "SINGLE"),
                    ("Married", "MARRIED"),
                    ("Divorced", "DIVORCED"),
                    ("Widowed", "WIDOWED"),
                    ("Separated", "SEPARATED"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[("Mr", "MR"), ("Mrs", "MRS"), ("Dr", "DR")],
                max_length=100,
            ),
        ),
    ]
